### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by austinginder** [iterate-ch/homebrew-cyberduck#1]
running "brew install iterate-ch/cyberduck/duck" returns the following.

```
==> Installing duck from iterate-ch/cyberduck
==> Downloading https://dist.duck.sh/nightly/duck-5.1.20382.tar.gz
==> Downloading from https://b1067d2246472fd1acfc-bc6e6f1143c33a3bad027dd01f822811.ssl.cf5.rackcdn.com/nightly/duck-5.1.20382.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "duck"
Download failed: https://b1067d2246472fd1acfc-bc6e6f1143c33a3bad027dd01f822811.ssl.cf5.rackcdn.com/nightly/duck-5.1.20382.tar.gz
```

**Comment by dkocher** [comment]
`osaka:~ dkocher$ brew upgrade iterate-ch/cyberduck/duck
==> Upgrading 1 outdated package, with result:
iterate-ch/cyberduck/duck 5.1.20385
==> Upgrading iterate-ch/cyberduck/duck
==> Downloading https://dist.duck.sh/nightly/duck-5.1.20385.tar.gz
==> Downloading from https://b1067d2246472fd1acfc-bc6e6f1143c33a3bad027dd01f822811.ssl.cf5.rackcdn.com/nightly/duck-5.1.20385.tar.gz
`

This has been resolved.

**Comment by austinginder** [comment]
Thanks!
