### ISSUE TITLE
Unable to install - error with brew command.

### ISSUE THREAD

**Issue by mathewbooth** [iterate-ch/homebrew-cyberduck#2]
I receive and error when running the brew install.

Error:

mb-mbp:~ mbp$ brew install iterate-ch/cyberduck/duck
==> Installing duck from iterate-ch/cyberduck
==> Downloading https://dist.duck.sh/duck-6.1.1.25620.tar.gz
==> Downloading from https://b1067d2246472fd1acfc-bc6e6f1143c33a3bad027dd01f822811.ssl.cf5.rackcdn.com/duck-6.1.1.25620.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "duck"
Download failed: https://dist.duck.sh/duck-6.1.1.25620.tar.gz

**Comment by dkocher** [comment]
Thanks for noticing. The download URI will be fixed with the next build.
