### ISSUE TITLE
duck  states (UNKNOWN_REVISION)

### ISSUE THREAD

**Issue by btazus** [iterate-ch/homebrew-cyberduck#3]
trying to synchronize from local HD to googledrive.  duck loaded from Brew.
This (UNKNOWN_REVISION) warning continues to show even after uninstalling and reinstalling duck.
This occurs on multiple computers running Mac OS 13.3, Apple Silicon.

Also whenever I run, I get many warn, info and error messages interspersed with help info.  Attached is zip of recent run
[duck-error-googledrive.txt.zip](https://github.com/iterate-ch/homebrew-cyberduck/files/11192219/duck-error-googledrive.txt.zip)

**Comment by btazus** [comment]
If I delete my brew installed copy and download the package from the website, duck will run in normal mode.
I also put this in a discussion group.

**Comment by dkocher** [comment]
> If I delete my brew installed copy and download the package from the website, duck will run in normal mode. I also put this in a discussion group.

We will follow up in iterate-ch/cyberduck#14497
